# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_address1', models.CharField(max_length=50)),
                ('property_address2', models.CharField(max_length=20)),
                ('property_address3', models.CharField(max_length=10)),
                ('property_address4', models.CharField(max_length=10)),
                ('unit_name', models.CharField(max_length=260)),
                ('tenant_name', models.CharField(max_length=150)),
                ('lease_start', models.CharField(max_length=50)),
                ('lease_end', models.CharField(max_length=50)),
                ('lease_years', models.IntegerField()),
                ('current_rent', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
