# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='lease_end',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='stats',
            name='lease_start',
            field=models.CharField(max_length=25),
        ),
    ]
